version: "3.8"

services:
  postgres-vector:
    image: ankane/pgvector:latest
    container_name: knock_db
    environment:
      POSTGRES_USER: knockuser
      POSTGRES_PASSWORD: knockpassword123
      POSTGRES_DB: knockprojectdb
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  pgdata:
